const steps = [
  {
    number: "01",
    title: "Share Your Mood",
    description: "Tell MoodFood how you're feeling — happy, stressed, tired, or inspired.",
  },
  {
    number: "02",
    title: "Add Ingredients",
    description: "Optionally upload a photo of ingredients from your kitchen or fridge.",
  },
  {
    number: "03",
    title: "Get Recommendations",
    description: "Receive personalized meal suggestions generated by AI in seconds.",
  },
  {
    number: "04",
    title: "Start Cooking",
    description: "Follow recipes and get assistance whenever you need it.",
  },
];

export function HowItWorks() {
  return (
    <section id="qanday-ishlaydi" className="py-20 md:py-28 bg-soft-gradient">
      <div className="container">
        <div className="mx-auto max-w-2xl text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-semibold tracking-tight text-balance">
            How it{" "}
            <span className="font-display italic text-primary">works</span>
          </h2>
          <p className="mt-4 text-lg text-foreground/70 text-pretty">
            From mood to meal in four simple steps.
          </p>
        </div>

        <div className="relative max-w-3xl mx-auto">
          <div
            aria-hidden="true"
            className="absolute left-6 sm:left-8 top-0 bottom-0 w-px bg-border"
          />
          <ol className="space-y-12">
            {steps.map((s) => (
              <li key={s.number} className="relative flex gap-6 sm:gap-10">
                <div className="relative shrink-0">
                  <div className="flex h-12 w-12 sm:h-16 sm:w-16 items-center justify-center rounded-2xl bg-card border border-border shadow-soft">
                    <span className="font-display text-2xl sm:text-3xl italic text-primary">
                      {s.number}
                    </span>
                  </div>
                </div>
                <div className="pt-2 sm:pt-4">
                  <h3 className="text-xl sm:text-2xl font-semibold tracking-tight">
                    {s.title}
                  </h3>
                  <p className="mt-2 text-foreground/65 leading-relaxed max-w-xl">
                    {s.description}
                  </p>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </div>
    </section>
  );
}
